### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Kammi61871** [Hexer10/VipMenu-Bonuses#11]
Release newest dev

CZE line 105
change
[code]
    "Get_Gravity"
    {
        "cze" Nyni mate mensi gravitaci"
    }
   [/code]
to
[code]
    "Get_Gravity"
    {
        "cze" "Nyni mate mensi gravitaci"
    }
    [/code]

in all translation files pls insert
[code]
	"Vip_Joined"
	{
	"en" "Vip is Joined"
	} 
[/code]

**Comment by Hexer10** [comment]
@ShawnCZek already pushed a pr
Thanks anyway

PS: On GitHub the goes goes in 

> ` `
