### ISSUE TITLE
Issue - After edit cfg files

### ISSUE THREAD

**Issue by afonsofsgomes** [Hexer10/VipMenu-Bonuses#15]
After edit cfg files of plugin, it stop working! 
Can not switch flag "a" to "o" - Stop Working
Can not disable some features on CFG Files - Stop Working 
Can not disable vip_core_root_default to "0" - Stop Working
When You install the plugin and do not switch nothing in cfg files it works, but try to change something in cfg files... It will stop working
Please try to solve it! 
Erros on Remote Console:
___________________________________________________________________________
AfonsoPranks-Youtuber: !vipmenu
L 10/01/2017 - 14:20:45: [SM] Exception reported: Language phrase "Menu_Respawn" not found
L 10/01/2017 - 14:20:45: [SM] Blaming: VipBonus.smx
L 10/01/2017 - 14:20:45: [SM] Call stack trace:
L 10/01/2017 - 14:20:45: [SM]   [0] VFormat
L 10/01/2017 - 14:20:45: [SM]   [1] Line 437, C:\Users\Hotel Abamar\AppData\Roaming\spedit\sourcepawn\configs\sm_1_8_5995\include\hexstocks.inc::AddMenuItemFormat
L 10/01/2017 - 14:20:45: [SM]   [2] Line 410, VipMenu.sp::vmenu
L 10/01/2017 - 14:20:45: [SM]   [3] Line 285, VipMenu.sp::Command_VipMenu

**Comment by Hexer10** [comment]
Fixed: https://github.com/Hexer10/VipMenu-Bonuses/commit/78441c6f7d0ce63e15d1956644b9b78125a04f31
https://github.com/Hexer10/VipMenu-Bonuses/commit/428e07508bd26edfe36b26ddae4ad02acf8dfc0b https://github.com/Hexer10/VipMenu-Bonuses/commit/c30b4be8dc830deb95007709ee3acd3457cf1052 https://github.com/Hexer10/VipMenu-Bonuses/commit/0fb37a6a343d67ebadb37decd38b18be732f3acb

Open a new issue if some problems persist.
