### ISSUE TITLE
Can't compile VipMenu.sp

### ISSUE THREAD

**Issue by ByKyTa** [Hexer10/VipMenu-Bonuses#17]
//// VipMenu.sp
//
// VipMenu.sp(119) : error 017: undefined symbol "Native_ResetItems"
// VipMenu.sp(128) : error 017: undefined symbol "AutoExecConfig_SetFile"
// VipMenu.sp(129) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
// VipMenu.sp(130) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(130) : warning 213: tag mismatch
// VipMenu.sp(131) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(131) : warning 213: tag mismatch
// VipMenu.sp(132) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(132) : warning 213: tag mismatch
// VipMenu.sp(133) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(133) : warning 213: tag mismatch
// VipMenu.sp(134) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(134) : warning 213: tag mismatch
// VipMenu.sp(135) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(135) : warning 213: tag mismatch
// VipMenu.sp(136) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(136) : warning 213: tag mismatch
// VipMenu.sp(137) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(137) : warning 213: tag mismatch
// VipMenu.sp(138) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(138) : warning 213: tag mismatch
// VipMenu.sp(139) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(139) : warning 213: tag mismatch
// VipMenu.sp(140) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(140) : warning 213: tag mismatch
// VipMenu.sp(141) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(141) : warning 213: tag mismatch
// VipMenu.sp(142) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(142) : warning 213: tag mismatch
// VipMenu.sp(143) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(143) : warning 213: tag mismatch
// VipMenu.sp(144) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(144) : warning 213: tag mismatch
// VipMenu.sp(145) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(145) : warning 213: tag mismatch
// VipMenu.sp(146) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(146) : warning 213: tag mismatch
// VipMenu.sp(147) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(147) : warning 213: tag mismatch
// VipMenu.sp(148) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(148) : warning 213: tag mismatch
// VipMenu.sp(149) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(149) : warning 213: tag mismatch
// VipMenu.sp(150) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(150) : warning 213: tag mismatch
// VipMenu.sp(151) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
// VipMenu.sp(151) : warning 213: tag mismatch
// VipMenu.sp(152) : error 017: undefined symbol "AutoExecConfig_CreateConVar"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.39 sec
// ----------------------------------------

**Comment by Hexer10** [comment]
You don't need to compile VipMenu.sp, just VipBonus.sp (That'll include VipMenu.sp) or download the compiled SMX from the releases tab.
